# Generated by Django 6.0.2 on 2026-02-27 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Адреса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Адреса клініки",
                "verbose_name_plural": "Адреси клінік",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Електронна пошта"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=255, verbose_name="ПІБ"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Номер телефону"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Електронна пошта"),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="ПІБ")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Номер телефону"),
                ),
                (
                    "is_adult",
                    models.BooleanField(default=True, verbose_name="Дорослий"),
                ),
                (
                    "visit_reason",
                    models.CharField(
                        choices=[
                            ("consultation", "📋 Консультація"),
                            ("acute_pain", "⚡ Гострий біль"),
                            ("filling_lost", "🦷 Випала пломба"),
                            ("prosthetics", "🦷 Протезування"),
                            ("implantation", "🔩 Імплантація"),
                            ("hygiene_adult", "✨ Чистка та Гігієна"),
                            ("therapy_adult", "🦷 Лікування (Пломба/Канали)"),
                            ("ortho_adult", "🔩 Протезування та Імплантація"),
                            ("surgery_adult", "💉 Видалення зуба"),
                            ("hygiene_child", "✨ Чистка молочних зубів"),
                            ("therapy_child", "🧸 Пломба/Лікування молочного зуба"),
                            ("surgery_child", "🦷 Видалення молочного зуба"),
                        ],
                        max_length=50,
                        verbose_name="Причина візиту",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "В очікуванні"),
                            ("completed", "Консультацію проведено"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "visit_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата візиту"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Hollywood.clinicaddress",
                        verbose_name="Адреса поліклініки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Запис",
                "verbose_name_plural": "Записи",
                "ordering": ["-visit_date"],
                "indexes": [
                    models.Index(fields=["email"], name="Hollywood_p_email_9dac08_idx")
                ],
            },
        ),
    ]
