# Generated by Django 6.0.2 on 2026-03-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hollywood", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientrecord",
            name="is_adult",
        ),
        migrations.AlterField(
            model_name="clinicaddress",
            name="address",
            field=models.CharField(
                choices=[
                    ("Овідіополь, Портова 13", "Овідіополь, Портова 13"),
                    ("Чорноморськ, проспект Миру 41", "Чорноморськ, проспект Миру 41"),
                ],
                max_length=255,
                unique=True,
                verbose_name="Адреса",
            ),
        ),
    ]
