# Generated by Django 6.0.2 on 2026-03-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Hollywood", "0002_remove_patientrecord_is_adult_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
    ]
